---
title: "BioMonTools Summary Report"
author: "`r Sys.getenv('USERNAME')`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: no
subtitle: Metric Scores and Values
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE)
# needed for trouble shooting
boo_DEBUG <- FALSE
if(boo_DEBUG==TRUE){
  # myConfig <- file.path(system.file(package="ContDataQC"), "extdata", "config.ORIG.R")
  # source(myConfig)
}## IF ~ boo_DEBUG ~ END
```

# DATA FILE INFORMATION
```{r data_file_info}
  # Results File
  df_metval <- read.csv("results_metval.csv")
  df_metsc <- read.csv("results_metsc.csv")
  lines_log <- readLines("results_log.txt")

  # Report Info
  myReportDate <- format(Sys.time(), '%Y-%m-%d %H:%M:%S')
  cat(paste("**Report Date:** " ,myReportDate, "\n\n", sep=""))
  myUser <- Sys.getenv("USERNAME")
  cat(paste("**Generated By:** ", myUser, "\n\n", sep=""))
  
  # Import Filename
  strFile <- gsub("^file = ", "", lines_log[3])
  cat("**Import Filename:** ", strFile, "\n\n", sep="")
  
  # Number of Samples
  myNumRecords <- nrow(df_metsc)
  cat(paste("**Number of Records:** ", myNumRecords, "\n\n", sep=""))
  
  # Period of Record
  if("Date" %in% names(df_metval$Date) == TRUE){
    POR <- paste(min(df_metval$Date)," to ", max(df_metval$Date), sep="")
  } else {
    POR <- "'Date' not retained in output"
  }
  cat(paste("**Period of Record:** ", POR, sep="", collapse="\n\n"))
```

# Log File
Any messages or warnings generated during the calculation of metric values and scores were saved in a log file.

The log file is shown below.

```{r Log}
# Read and Display
readLines("results_log.txt")
```

# Results, Metric Scores

## Plot
```{r Results_Index_Plot}
# Packages
library(ggplot2)

# Data
df_metsc <- read.csv("results_metsc.csv")

# default bin width is 1/30 of range
# need to specify to avoid warning about bins = 30.
range_div30 <- (max(df_metsc$Index, na.rm = TRUE) - min(df_metsc$Index, na.rm = TRUE))/30

# Plot
p1 <- ggplot(df_metsc, aes(Index), fill=INDEX_REGION, shape=INDEX_REGION) +
            geom_dotplot(aes_string(fill="INDEX_REGION"), method="histodot", binwidth = range_div30) +
            labs(x="Index Value"
                 , title = "Index values by region.") +
            theme(axis.title.y=element_blank()
                  , axis.ticks.y=element_blank()
                 , axis.text.y=element_blank()
                  )

# Output
p1
```

## Map
Only get map if Lat and Long is included.
Need to modify Shiny app to include Lat, Latitude, etc as saved fields.
Use regular expressions to capture.

```{r Results_Index_Map}
# Packages

# Data
df_metsc <- read.csv("results_metsc.csv")

# Output
cat(paste("**Index Scores, Map:**", sep="", collapse="\n\n"))
cat("No coordinates available to generate map.")
```

